header:
  version: 11

machine: stompduck2
distro: kiss
target:
  - kiss-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    refspec: "2.0"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    refspec: kirkstone
    layers:
      meta:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    refspec: kirkstone
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-kiss:
    layers:
      meta-kiss:

local_conf_header:
  meta-kiss: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
